version: 2.1
orbs:
  salesforce-sfdx: circleci/salesforce-sfdx@2.2.0
  
jobs:
  create-open:
    executor: default
    steps:
      - checkout
      - install
      - sfdx/auth:
          defaultusername: $SC_ORG_USER
      - sfdx/scratch-create:
          scratch-alias: SC_ORG
          scratch-config: ./config/project-scratch-def.json
      - sfdx/scratch-open:
          scratch-alias: SC_ORG
      - sfdx/scratch-delete:
          scratch-alias: $SC_ORG_USER

workflows:
  basic-test:
    jobs:
      - create-open
